import Head from "next/head";
import HeaderHomePage from "~/components/HomePage/HeaderHomePage";
import Services from "~/components/HomePage/Services";
import { LayoutBody } from "~/components/Layout/LayoutBody";
import OurServices from "~/lib/content/ourServices";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Scale Up</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <LayoutBody>
        <HeaderHomePage />
        <Services OurServices={OurServices} />
      </LayoutBody>
    </div>
  );
};

export default Home;
