import type { NextPage } from "next";
import Head from "next/head";
import HeaderHomePage from "~/components/HomePage/HeaderHomePage";
import { LayoutBody } from "~/components/Layout/LayoutBody";
import { LayoutContent } from "~/components/Layout/LayoutContent";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <LayoutBody>
        <LayoutContent>
          <HeaderHomePage />
        </LayoutContent>
      </LayoutBody>
    </div>
  );
};

export default Home;
